name: Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run test:lint
    - run: tar -cvf build.tar .
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: build.tar
    - run: rm build.tar & rm -rvf ./.git/ & rm .gitignore
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: .
        target_branch: develop-builds
        verbose: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}